# Generated by Django 5.1.4 on 2026-07-17 18:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='avatars/%Y/%m/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-Binary'), ('PNS', 'Prefer Not to Say')], default='', max_length=5)),
                ('occupation', models.CharField(blank=True, default='', max_length=255)),
                ('role', models.CharField(choices=[('user', 'User'), ('therapist', 'Therapist'), ('admin', 'Admin')], db_index=True, default='user', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False, help_text='True after email verification is completed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WellnessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sleep_schedule', models.JSONField(blank=True, default=dict, help_text='e.g. {"bedtime": "22:30", "wake_time": "06:30"}')),
                ('stress_level', models.PositiveSmallIntegerField(default=5, help_text='Self-reported stress level 1 (low) – 10 (high)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('primary_goals', models.JSONField(blank=True, default=list, help_text='e.g. ["reduce anxiety", "better sleep", "build confidence"]')),
                ('wellness_preferences', models.JSONField(blank=True, default=list, help_text='e.g. ["breathing exercises", "journaling", "meditation"]')),
                ('onboarding_done', models.BooleanField(default=False, help_text='True once user completes the onboarding wizard.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wellness Profile',
                'verbose_name_plural': 'Wellness Profiles',
            },
        ),
    ]
