# Generated by Django 5.1.4 on 2026-08-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscriptionplan_wellnessresource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consultation_fee',
            field=models.CharField(blank=True, default='₹1,500 / 45 mins', max_length=100),
        ),
    ]
