"""
ManMitra — Wellness Plan Model
Structured routines and tasks (daily or weekly) designed to guide the user towards their goals.
"""
import uuid
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class WellnessPlan(models.Model):
    """
    Personalized daily/weekly routine generated based on user wellness profile and mood trends.
    """

    class PlanType(models.TextChoices):
        DAILY = 'daily', 'Daily Routine'
        WEEKLY = 'weekly', 'Weekly Plan'

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='wellness_plans',
        db_index=True,
    )

    plan_type = models.CharField(
        max_length=10,
        choices=PlanType.choices,
        default=PlanType.DAILY,
        db_index=True,
    )

    # ── Structured Tasks & Schedules ─────────────────────────────────────────
    # Format:
    # {
    #   "tasks": [
    #     {"time": "07:00", "title": "Breathing Exercise", "duration_mins": 10, "completed": false},
    #     {"time": "21:30", "title": "Gratitude Journaling", "duration_mins": 15, "completed": false}
    #   ]
    # }
    content = models.JSONField(
        default=dict,
        help_text='Structured JSON representing specific exercises, habits, and tasks.',
    )

    generated_by_ai = models.BooleanField(
        default=True,
        help_text='True if the plan was generated by the AI wellness coordinator engine.',
    )
    
    # ── Temporal scope (especially for weekly plans) ──────────────────────────
    week_start = models.DateField(
        null=True,
        blank=True,
        help_text='Calendar starting date for weekly routines.',
    )

    is_active = models.BooleanField(
        default=True,
        db_index=True,
        help_text='Flag to toggle active state or archive older plans.',
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Wellness Plan'
        verbose_name_plural = 'Wellness Plans'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['user', 'plan_type', 'is_active']),
        ]

    def __str__(self) -> str:
        return f'{self.get_plan_type_display()} for {self.user.full_name} ({self.created_at.date()})'
