# Generated by Django 5.1.4 on 2026-07-17 18:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_type', models.CharField(choices=[('daily', 'Daily Routine'), ('weekly', 'Weekly Plan')], db_index=True, default='daily', max_length=10)),
                ('content', models.JSONField(default=dict, help_text='Structured JSON representing specific exercises, habits, and tasks.')),
                ('generated_by_ai', models.BooleanField(default=True, help_text='True if the plan was generated by the AI wellness coordinator engine.')),
                ('week_start', models.DateField(blank=True, help_text='Calendar starting date for weekly routines.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Flag to toggle active state or archive older plans.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wellness Plan',
                'verbose_name_plural': 'Wellness Plans',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'plan_type', 'is_active'], name='wellness_we_user_id_be2074_idx')],
            },
        ),
    ]
