# Generated by Django 5.1.4 on 2026-07-17 18:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_keywords', models.JSONField(blank=True, default=list, help_text='List of exact keywords/phrases that triggered the event.')),
                ('severity', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical / Immediate Danger')], default='high', max_length=15)),
                ('resources_shown', models.JSONField(blank=True, default=dict, help_text='JSON record of help hotlines and info shown to the user.')),
                ('resolved', models.BooleanField(db_index=True, default=False, help_text='True if support staff marked the incident as reviewed/resolved.')),
                ('flagged_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crisis_reports', to='chat.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crisis_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crisis Report',
                'verbose_name_plural': 'Crisis Reports',
                'ordering': ['-flagged_at'],
            },
        ),
    ]
