# Generated by Django 5.1.4 on 2026-07-17 18:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mood_score', models.PositiveSmallIntegerField(help_text='Numeric mood intensity: 1 (very low) to 10 (very high).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('mood_label', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('calm', 'Calm'), ('angry', 'Angry'), ('neutral', 'Neutral'), ('excited', 'Excited'), ('tired', 'Tired'), ('grateful', 'Grateful'), ('overwhelmed', 'Overwhelmed'), ('hopeful', 'Hopeful'), ('frustrated', 'Frustrated')], help_text='Qualitative emotion label.', max_length=20)),
                ('note', models.TextField(blank=True, default='', help_text='Optional free-text note from the user about their mood.')),
                ('ai_insight', models.TextField(blank=True, default='', help_text='AI-generated empathetic reflection (populated in Phase 3).')),
                ('date', models.DateField(auto_now_add=True, db_index=True, help_text='The calendar date of the check-in (for streak/daily aggregations).')),
                ('logged_at', models.DateTimeField(auto_now_add=True, help_text='Exact timestamp of the check-in.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mood Log',
                'verbose_name_plural': 'Mood Logs',
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='mood_moodlo_user_id_3c7c32_idx'), models.Index(fields=['user', 'logged_at'], name='mood_moodlo_user_id_1afc91_idx')],
            },
        ),
    ]
