# Generated by Django 5.1.4 on 2026-07-17 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodlog',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today, help_text='The calendar date of the check-in (for streak/daily aggregations).'),
        ),
    ]
