# Generated by Django 5.1.4 on 2026-07-17 18:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mood', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='Untitled Entry', max_length=255)),
                ('_encrypted_content', models.TextField(db_column='content', help_text='Encrypted journal content stored at rest.')),
                ('sentiment_score', models.FloatField(default=0.0, help_text='AI-analyzed sentiment score between -1.0 (very negative) and 1.0 (very positive).')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mood_tag', models.ForeignKey(blank=True, help_text='Optional link to a mood log logged around the same time.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_journals', to='mood.moodlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='journal_jou_user_id_9e5be0_idx')],
            },
        ),
    ]
